CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS providers (id TEXT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS models (id TEXT PRIMARY KEY, provider_id TEXT REFERENCES providers(id), capabilities JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS usage (id BIGSERIAL PRIMARY KEY, model_id TEXT REFERENCES models(id), tokens_used INTEGER NOT NULL, latency_ms NUMERIC NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS costs (id BIGSERIAL PRIMARY KEY, model_id TEXT REFERENCES models(id), amount NUMERIC NOT NULL, currency TEXT NOT NULL DEFAULT 'USD', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memories (id TEXT PRIMARY KEY, memory_type TEXT NOT NULL, content TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memory_audit (id BIGSERIAL PRIMARY KEY, memory_id TEXT NOT NULL, action TEXT NOT NULL, actor TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memory_versions (id BIGSERIAL PRIMARY KEY, memory_id TEXT NOT NULL, version INTEGER NOT NULL, content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memory_reviews (id BIGSERIAL PRIMARY KEY, memory_id TEXT NOT NULL, status TEXT NOT NULL, risk_score NUMERIC NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS repositories (id BIGSERIAL PRIMARY KEY, url TEXT NOT NULL UNIQUE, metadata JSONB NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS commits (id TEXT PRIMARY KEY, repository_id BIGINT REFERENCES repositories(id), message TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS issues (id BIGSERIAL PRIMARY KEY, repository_id BIGINT REFERENCES repositories(id), title TEXT NOT NULL, state TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pull_requests (id BIGSERIAL PRIMARY KEY, repository_id BIGINT REFERENCES repositories(id), title TEXT NOT NULL, state TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS dependencies (id BIGSERIAL PRIMARY KEY, repository_id BIGINT REFERENCES repositories(id), name TEXT NOT NULL, version TEXT);
CREATE TABLE IF NOT EXISTS architecture_decisions (id BIGSERIAL PRIMARY KEY, title TEXT NOT NULL, status TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS architecture_reviews (id BIGSERIAL PRIMARY KEY, decision_id BIGINT REFERENCES architecture_decisions(id), risk_score NUMERIC NOT NULL, status TEXT NOT NULL);
